name: mp3
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  sqflite: ^2.3.0
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flashcards.json
